version: "3"

services:
  postgresql:
    image: bitnami/postgresql
    restart: always
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: junbuck@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1111
    volumes:
      - ~/data/postgres:/var/lib/pgadmin/storage
